### ISSUE TITLE
Suggestions: Improved Fraction Feature

### ISSUE THREAD

**Issue by tderkert** [impallari/Libre-Franklin#10]
A suggestion to make the fraction feature a bit more clever. 
Instead of turning `1 1/2` into  `¹ ½` as Glyphs auto generated feature does you could have it convert it to `1 ½`  so that it only modifies the glyphs adjacent to the fraction-slash.

[This a Fraction feature code](https://github.com/cph-typo/resources/blob/master/OpenType%20Feature%20Snippets/frac.fea) that Tal Leming wrote, with some minor edits for Glyphs glyph naming convention.

`1 1/2` turns to this: 
![image](https://cloud.githubusercontent.com/assets/6050484/17585954/1f3d9476-5fbf-11e6-9d72-6a22aace77a2.png)

**Comment by impallari** [comment]
Thanks, but No.
