### ISSUE TITLE
Left double quote (“) character displays poorly in italic versions

### ISSUE THREAD

**Issue by davidakennedy** [impallari/Libre-Franklin#18]
Thank you for making Libre Franklin! It's going to be used in the next default theme for WordPress, called Twenty Seventeen – to be released soon.

An issue was reported about the left double quote not displaying right in italic versions. See [this ticket](https://core.trac.wordpress.org/ticket/38775).

The two quote marks seem to display on top of one another. At body text size for Twenty Seventeen, the left double quote is pretty much indistinguishable from the left single quote.

Screenshot:

![bad-glyph](https://cloud.githubusercontent.com/assets/1473618/20287188/5de24a8a-aacb-11e6-94a4-14928d6af3a2.jpeg)

**Comment by impallari** [comment]
Hi David,
Thanks for reporting the issue, I will fix it a upload a new version in a few minutes, and hopefully it can be pushed to googlefonts this week.
Also, great news about making it the default font in Wordpress!!

**Comment by impallari** [comment]
v4.015 just uploaded.
Pinging @m4rc1e so it gets uploaded to GF soon.

**Comment by davidakennedy** [comment]
Awesome, thank you @impallari!

**Comment by harryhorton** [comment]
Was this uploaded to GF? We're still experiencing the issue. @impallari
