### ISSUE TITLE
Cyrillic for Libre-Fraklin

### ISSUE THREAD

**Issue by StefanPeev** [impallari/Libre-Franklin#19]
Here are the preview and attachments with the source file, OTF file and UFO files for **LibreFranklin-Thin** with **Basic Cyrillic**. Please preview and consider including of the Cyrillic or give your suggestions for improvement.

![librefranklin_01](https://cloud.githubusercontent.com/assets/12949369/22455301/31af3814-e794-11e6-997d-0224dcd60eb0.jpg)

[LibreFranklin-Thin.zip](https://github.com/impallari/Libre-Franklin/files/741281/LibreFranklin-Thin.zip)

**Comment by impallari** [comment]
Hi Stefan, thanks! Can you do it for the Heavy style too? 
That way we can interpolate and generate the whole family.

**Comment by davelab6** [comment]
Yeah for Google Fonts I need same charset in all styles

Cc @alexeiva

**Comment by StefanPeev** [comment]
@impallari @davelab6 OK! I'll do the Cyrillic step by step. First I'll add Cyrillic local features for Bulgarian, Serbian, Macedonian in **thin** version, than I'll do the same for the **black** version and according to them in **thin italic** and **black italic**.

**Comment by StefanPeev** [comment]
@impallari Hi Pablo! I've uploaded pre-release version of Cyrillic Script for LibreFranklin-Thin through PR option. You could have a look at it. There is still more work to be done but my intention is Libre Franklin to cover GF Cyrillic plus requirements. I think it will be better not to start my work on the black version before your notices about the thin one. In a day or two I'll finish my corrections on the thin version and will upload my final offer. Meanwhile any suggestions are wellcome.

**Comment by StefanPeev** [comment]
I'm preparing an updated to LibreFranklin-Thin. It's not finalized yet but I hope it's going in the right direction: resolving the issues with proportions, metrics and glyph set coverage also according to @alexeiva remarks. Here is a preview.

![librefranklin_02](https://cloud.githubusercontent.com/assets/12949369/23157902/a663d696-f825-11e6-9959-3597501b9b2c.jpg)

**Comment by gonzoMD** [comment]
Hello everybody.

I am member of the ReactOS development team and we use your font as a free/libre replacement for "MS Franklin Gothic" Font. Thank you so far for your work.
Because we have many russian testers which ask whether it is possible to add cyrillic glyphs too, I ask you if this issue will be worked on further or not? 

Best regards

**Comment by StefanPeev** [comment]
@gonzoMD @impallari @davelab6 @crystaltype I've sent my revised proposal for LibreFranklin-Thin with Cyrillic Script as a PR and I'm waiting for the answer. If the answer is positive, I'm ready to continue my work on Cyrillic script for LibreFranklin.

**Comment by pyotr** [comment]
Hi @StefanPeev i saw your work too late it seems :(
Do u have any progress since last year with this project?
Thank u!

**Comment by StefanPeev** [comment]
@pyotr Alexei Vanyasin is responsible for the Cyrillic alphabet. You can see the current Cyrillic variants in his [repository](https://github.com/alexeiva/Libre-Franklin).

**Comment by pyotr** [comment]
Thank you!!

**Comment by pyotr** [comment]
@StefanPeev @petr-akhlamov Thanks a lot!!

**Comment by StefanPeev** [comment]
@petr-akhlamov @pyotr I'm not sure if it is correct to PR Libre-Franklin Cyrillic without asking Alexei Vanyashin first. I personally desagree with such attitude.

**Comment by alexeiva** [comment]
@petr-akhlamov @pyotr no problem. You can simply use [v1.501 release ](https://github.com/alexeiva/Libre-Franklin/releases/tag/1.501)
