### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by davelab6** [impallari/Libre-Franklin#2]
There are some problems with the way the OTFs are handled. Please can you...
- [x] fix the naming to be normal, no numbers
- [x] fix the ExtraLight to weightClass 275, 
- [x] fix the spelling of 'Ligth' is to 'Light' in both Light and ExtraLight
- [x] fix the family naming according to https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0
- [x] generate TTFs and run ttfautohint on them
- [x] push a new version

cc @felipesanches

**Comment by impallari** [comment]
Thanks
The stem value in the font file name is only for the betas, to have then alphabetically order while I'm working. It will removed on the v1 release, of course.

**Comment by impallari** [comment]
@davelab6 please give me editing permission on that spreadsheet so I can add a the name of the "custom parameters" needed for the Glyphs App

**Comment by davelab6** [comment]
Done :)
