### ISSUE TITLE
dot accent on "e" is not properly centered

### ISSUE THREAD

**Issue by bubble23** [impallari/Libre-Franklin#22]
look here

![snimek obrazovky 2017-05-16 v 12 30 37](https://cloud.githubusercontent.com/assets/7462746/26102008/916a3dca-3a33-11e7-97e7-560526a6994a.png)

**Comment by alexeiva** [comment]
Hi Pablo, if you don't mind I fixed this in https://github.com/impallari/Libre-Franklin/pull/23/commits/ddde8f3ffea62b6d39ac43acc992928347cf7ca2

<img width="572" alt="screen shot 2018-03-30 at 4 56 15 pm" src="https://user-images.githubusercontent.com/16634089/38138333-6f78f50a-343b-11e8-858f-17685b74d0ca.png">
<img width="590" alt="screen shot 2018-03-30 at 4 55 18 pm" src="https://user-images.githubusercontent.com/16634089/38138334-7304b920-343b-11e8-96c9-62e4a9e9ef64.png">

**Comment by Moilleadoir** [comment]
Actually there are problems with some other dotted letters, e.g. those used in Irish…
![Libre Franklin poncanna](https://user-images.githubusercontent.com/1229543/54252307-5d102800-459e-11e9-84c1-19f5735bfe72.jpg)
The **ṁ** doesn’t _look_ centred (though maybe it is) and it’s more usual to put the dot over the bowl if there is one, not the stem (**ḃ** & **ḋ** should be like **ċ** & **ṗ**). In GIMP they look OK, but look at how they appear in LibreOffice Writer…
![Libre Franklin poncanna LibreOffice](https://user-images.githubusercontent.com/1229543/54252473-1838c100-459f-11e9-8f24-f70f2c495d1e.jpg)
Bizarre.
