### ISSUE TITLE
'emptyset' glyph?

### ISSUE THREAD

**Issue by davelab6** [impallari/Libre-Franklin#6]
Why is the 'emptyset' glyph included in your glyph set?

**Comment by davelab6** [comment]
@impallari ping

**Comment by impallari** [comment]
It was the only one missing from the Glyphsapp Math defaults.
It is quick and easy to draw, so I added it.
![screen shot 2016-06-30 at 22 25 06](https://cloud.githubusercontent.com/assets/3036973/16509290/8b6f50a4-3f11-11e6-83c7-19a245d9834f.png)

**Comment by davelab6** [comment]
cc @kalapi @alexeiva

**Comment by davelab6** [comment]
Thanks @impallari that sounds good

**Comment by alexeiva** [comment]
It is an important LaTeX glyph. I will add this

http://tex.stackexchange.com/questions/22798/nice-looking-empty-set
